### ISSUE TITLE
Fontemon map looks kind of like a d***

### ISSUE THREAD

**Issue by Bee4Queer** [mmulet/font-game-engine#7]
yeah my (no longer)(not because of this) friend saw me playing fontemon on the bus and thought that the map looked like that 0_o

**Comment by leahanderson1** [comment]
WAIT WHAT
the wildest random encounter ever

**Comment by Bee4Queer** [comment]
how tf did you find this and wait what there's no way that's from only a bit over a year ago

**Comment by leahanderson1** [comment]
i  heard about fontemon and then looked at the issues and then i saw yours 😭
